name: TTBDebugPlus
options:
  bundleIdPrefix: com.tuantruong
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    GENERATE_INFOPLIST_FILE: false
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1

targets:
  TTBDebugPlus:
    type: application
    platform: macOS
    sources:
      - path: TTBDebugPlus
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tuantruong.TTBDebugPlus
        PRODUCT_NAME: TTBDebugPlus
        INFOPLIST_FILE: TTBDebugPlus/Info.plist
        CODE_SIGN_ENTITLEMENTS: TTBDebugPlus/TTBDebugPlus.entitlements
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: true
        SWIFT_EMIT_LOC_STRINGS: true
        ENABLE_PREVIEWS: true
