//
//  FeedbackViewModel.swift
//  TTBDebugPlus
//
//  Created by TuanTruong on 2026-03-27.
//  Manages feedback reports with form state, screenshot attachment, and export
//

import SwiftUI
import AppKit

// MARK: - Feedback ViewModel
@Observable
final class FeedbackViewModel {
    
    // MARK: - State
    var reports: [FeedbackReport] = []
    var selectedReport: FeedbackReport? = nil
    
    // Form state
    var formTitle: String = ""
    var formDescription: String = ""
    var formTag: FeedbackTag = .uiux
    var formScreenshots: [NSImage] = []
    
    // MARK: - Create Report
    func submitReport(deviceName: String? = nil) {
        let report = FeedbackReport(
            title: formTitle,
            description: formDescription,
            tag: formTag,
            screenshots: formScreenshots,
            deviceName: deviceName ?? "Unknown Device",
            timestamp: Date()
        )
        reports.insert(report, at: 0)
        selectedReport = report
        clearForm()
    }
    
    func clearForm() {
        formTitle = ""
        formDescription = ""
        formTag = .uiux
        formScreenshots.removeAll()
    }
    
    func attachScreenshot(_ image: NSImage) {
        formScreenshots.append(image)
    }
    
    func removeScreenshot(at index: Int) {
        guard index < formScreenshots.count else { return }
        formScreenshots.remove(at: index)
    }
    
    // MARK: - Resolve Report
    func toggleResolve(_ report: FeedbackReport) {
        if let idx = reports.firstIndex(where: { $0.id == report.id }) {
            reports[idx].isResolved.toggle()
            if selectedReport?.id == report.id {
                selectedReport = reports[idx]
            }
        }
    }
    
    func deleteReport(_ report: FeedbackReport) {
        reports.removeAll { $0.id == report.id }
        if selectedReport?.id == report.id {
            selectedReport = nil
        }
    }
    
    // MARK: - Export as Markdown
    func exportMarkdown(for report: FeedbackReport) -> String {
        var md = """
        # Bug Report: \(report.title)
        
        **Tag:** \(report.tag.rawValue)
        **Status:** \(report.isResolved ? "Resolved ✅" : "Open 🔴")
        **Device:** \(report.deviceName)
        **Date:** \(report.formattedDate)
        
        ---
        
        ## Description
        
        \(report.description)
        
        """
        
        if !report.screenshots.isEmpty {
            md += """
            
            ## Screenshots
            
            \(report.screenshots.count) screenshot(s) attached.
            
            """
        }
        
        md += """
        
        ---
        *Generated by TTBDebugPlus v2.3.0*
        """
        
        return md
    }
    
    // MARK: - Export Report
    func exportReport(_ report: FeedbackReport) {
        let markdown = exportMarkdown(for: report)
        
        let panel = NSSavePanel()
        panel.allowedContentTypes = [.plainText]
        panel.nameFieldStringValue = "BugReport_\(report.title.replacingOccurrences(of: " ", with: "_")).md"
        
        panel.begin { response in
            if response == .OK, let url = panel.url {
                try? markdown.write(to: url, atomically: true, encoding: .utf8)
            }
        }
    }
    
    // MARK: - Share Report
    func shareReport(_ report: FeedbackReport) {
        let markdown = exportMarkdown(for: report)
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(markdown, forType: .string)
    }
    
}


// MARK: - Models

struct FeedbackReport: Identifiable {
    let id = UUID()
    var title: String
    var description: String
    var tag: FeedbackTag
    var screenshots: [NSImage]
    var deviceName: String
    var timestamp: Date
    var isResolved: Bool = false
    
    var formattedDate: String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd HH:mm"
        return formatter.string(from: timestamp)
    }
    
    var relativeTime: String {
        let interval = Date().timeIntervalSince(timestamp)
        if interval < 60 { return "Just now" }
        if interval < 3600 { return "\(Int(interval / 60)) min ago" }
        if interval < 86400 { return "\(Int(interval / 3600)) hours ago" }
        return formattedDate
    }
}

enum FeedbackTag: String, CaseIterable {
    case uiux = "UI/UX"
    case network = "Network"
    case crash = "Crash"
    case performance = "Performance"
    case other = "Other"
    
    var color: Color {
        switch self {
        case .uiux: return .ttPrimary
        case .network: return .ttError
        case .crash: return .red
        case .performance: return .ttWarning
        case .other: return .ttTextSecondary
        }
    }
    
    var icon: String {
        switch self {
        case .uiux: return "paintbrush"
        case .network: return "network"
        case .crash: return "exclamationmark.triangle"
        case .performance: return "gauge.high"
        case .other: return "tag"
        }
    }
}
