# Uncomment the next line to define a global platform for your project

platform :ios, '10.0'

target 'TTBaseUIKitExample' do
  use_frameworks!
      pod 'TTBaseUIKit', :path => '../TTBaseUIKit/TTBaseUIKit.podspec'
end
